name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  nucleoid:
    uses: GreyCollar/GreyCollar/.github/workflows/deploy.yml@main
    with:
      service_name: 'nucleoid.com'
      environment: 'live'
      install_dependencies: true
      run_build: true
    secrets: 
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
